// import 'package:flutter/material.dart';

// final Map<String, IconData> availableIcons = {
//   'fastfood': Icons.fastfood,
//   'commute': Icons.commute,
//   'movie': Icons.movie,
//   'shopping_cart': Icons.shopping_cart,
//   'fitness_center': Icons.fitness_center,
//   'savings': Icons.savings,
//   'category': Icons.category,
//   'coffee': Icons.coffee,
//   'local_cafe': Icons.local_cafe,
//   'restaurant': Icons.restaurant,
//   'directions_car': Icons.directions_car,
//   'directions_bike': Icons.directions_bike,
//   'local_gas_station': Icons.local_gas_station,
//   'flight': Icons.flight,
//   'train': Icons.train,
//   'local_hospital': Icons.local_hospital,
//   'home': Icons.home,
//   'phone': Icons.phone,
//   'computer': Icons.computer,
//   'movie_filter': Icons.movie_filter,
//   'music_note': Icons.music_note,
//   'sports_soccer': Icons.sports_soccer,
//   'book': Icons.book,
//   'local_library': Icons.local_library,
//   'pets': Icons.pets,
//   'local_florist': Icons.local_florist,
//   'toys': Icons.toys,
//   'school': Icons.school,
//   'work': Icons.work,
//   'local_offer': Icons.local_offer,
//   'credit_card': Icons.credit_card,
//   'account_balance': Icons.account_balance,
//   'build': Icons.build,
//   'local_mall': Icons.local_mall,
//   'brush': Icons.brush,
//   'cake': Icons.cake,
//   'child_care': Icons.child_care,
//   'directions_run': Icons.directions_run,
//   'emoji_events': Icons.emoji_events,
//   'event': Icons.event,
//   'extension': Icons.extension,
//   'golf_course': Icons.golf_course,
//   'headphones': Icons.headphones,
//   'healing': Icons.healing,
//   'keyboard': Icons.keyboard,
//   'local_pizza': Icons.local_pizza,
//   'mic': Icons.mic,
//   'nightlife': Icons.nightlife,
//   'pool': Icons.pool,
//   'restaurant_menu': Icons.restaurant_menu,
//   'spa': Icons.spa,
//   'star': Icons.star,
//   'videogame_asset': Icons.videogame_asset,
//   'watch': Icons.watch,
// };

import 'package:flutter/material.dart';
import 'package:jaibee1/data/models/category.dart';
import 'package:jaibee1/l10n/s.dart';

String getLocalizedCategory(String name, S localizer) {
  final map = {
    'food': localizer.food,
    'transport': localizer.transport,
    'transportation': localizer.transport,
    'entertainment': localizer.entertainment,
    'coffee': localizer.coffee,
    'income': localizer.income,
    'shopping': localizer.shopping,
    'travel': localizer.travel,
    'education': localizer.education,
    'health': localizer.health,
    'bills': localizer.bills,
    'groceries': localizer.groceries,
    'beauty': localizer.beauty,
    'electronics': localizer.electronics,
    'books': localizer.books,
    'petcare': localizer.petCare,
    'gifts': localizer.gifts,
    'home': localizer.home,
    'savings': localizer.savings,
    'events': localizer.events,
    'fitness': localizer.fitness,
    'other': localizer.other,
  };
  return map[name.toLowerCase()] ?? name;
}

IconData getCategoryIcon(Category category) {
  const iconMap = {
    'shopping_cart': Icons.shopping_cart,
    'local_hospital': Icons.local_hospital,
    'directions_car': Icons.directions_car,
    'restaurant': Icons.restaurant,
    'school': Icons.school,
    'movie': Icons.movie,
    'fitness_center': Icons.fitness_center,
    'flight': Icons.flight,
    'home': Icons.home,
    'credit_card': Icons.credit_card,
    'local_mall': Icons.local_mall,
    'spa': Icons.spa,
    'computer': Icons.computer,
    'book': Icons.book,
    'pets': Icons.pets,
    'cake': Icons.cake,
    'savings': Icons.savings,
    'event': Icons.event,
    'attach_money': Icons.attach_money,
  };
  return iconMap[category.icon] ?? Icons.category;
}
